Preset mGAP filtering
BimberLab/DiscvrLabKeyModules pull request #96
Opened 2021-09-28 20:47 UTC by jctrotter

Adds the ability to filter displayed data through a custom widget. Currently filters by two preset filters, can be modified through editing code base. Users currently cannot create new filters.

2021-09-28 22:01 UTC, bbimber requested changes

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantDisplay/model.js
> +               console.log(getContainingTrack(self))
do we need the logging?

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantDisplay/model.js
> +            self.renderProps().config.filters.set(filter)
this kind of stuff might need a better pattern. if config.filters is absent, this will error. is there a more generalized solution besides layers of checking whether config != null, config.filters != null, etc?

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantRenderer/components/SvgFeatureRendering.js
> +   if(filters["af02"]){
Can you have a public FilterMap object or something? This way the UI and the filter code can work off the same definitions?

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantRenderer/components/SvgFeatureRendering.js
> +    if(isFiltered(feature, filters)){
Generally speaking, i would expect a function named "isFiltered" to return true if the feature is filtered, and false if not. The logic is reversed here?

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/FilterWidget/FilterWidget.js
> +                 <FormControlLabel className={classes.filterOption} control={<Checkbox checked={af02} onChange={handleChange} name="af02"/>} label="AF > 0.2" />
If we cant make this totally generic (i.e. defining a filter as name, accessor, operator, value), can you at least make a separate "FilterTypes" file, which is loaded here and also loaded in the filtering code? This could have one definition of each available filter, maintained in one place

2021-09-28 22:01 UTC, bbimber commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/FilterWidget/FilterWidget.js
> +      const { af02, impactHigh } = state;
isnt this another case where having one const that's a map, and giving it properties like af02: true, impactHigh: false is inherently more flexible? As a result, if you're creating a const with a very specific purpose, it's probably not a good idea

2021-09-29 19:56 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/FilterWidget/FilterWidget.js
> +      const { af02, impactHigh } = state;
Updated

2021-09-29 19:56 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/FilterWidget/FilterWidget.js
> +                 <FormControlLabel className={classes.filterOption} control={<Checkbox checked={af02} onChange={handleChange} name="af02"/>} label="AF > 0.2" />
Updated

2021-09-29 19:56 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantRenderer/components/SvgFeatureRendering.js
> +    if(isFiltered(feature, filters)){
Renamed to "isDisplayed"

2021-09-29 19:57 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantRenderer/components/SvgFeatureRendering.js
> +   if(filters["af02"]){
Updated

2021-09-29 20:02 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantDisplay/model.js
> +               console.log(getContainingTrack(self))
Removed

2021-09-29 20:17 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantDisplay/model.js
> +            self.renderProps().config.filters.set(filter)
We could wrap it in a try/catch block for some null handling behavior. However with this PR my understanding is that renderProps().config.filters will only be absent if "filters" is removed from ExtendedVariantRenderer/configSchema. Is there a case where config.filters is confirmed absent?

2021-09-29 21:17 UTC, jctrotter commented on jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantDisplay/model.js
> +            self.renderProps().config.filters.set(filter)
updated

2021-10-22 01:11 UTC, closed without merging